branch-defaults:
  master:
    environment: dev-env
    group_suffix: null
global:
  application_name: java-getting-started
  branch: null
  default_ec2_keyname: null
  default_platform: Java 8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
deploy:
  artifact: target/java-getting-started-1.0.jar
